Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Controllers/AlbumController.cs
using Lab_MVC_med_Javascript_och_Ajax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_MVC_med_Javascript_och_Ajax.Controllers
{
    public class AlbumController : Controller
    {
        GalleryDbContext db = new GalleryDbContext();
        // GET: Album
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(AlbumViewModels Album)
        {
            Album.Id = new Guid();
            if (ModelState.IsValid)
            {
                db.AlbumViewModels.Add(Album);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(Album);
        }
    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_MVC_med_Javascript_och_Ajax.Controllers
{
    public class HomeController : Controller
    {
        GalleryDbContext db = new GalleryDbContext();
        public ActionResult Index()
        {
            var Albums = db.AlbumViewModels.ToList();
            return View(Albums);
        }
        public ActionResult Information()
        {
            return View();
        }
        public ActionResult Test() { Dictionary<string, object> data = new Dictionary<string, object>(); data.Add("Placeholder", "Placeholder"); return View(data); }


    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>StartPage</h2>
<div>@Html.ActionLink("Add new Album", "Create", "Album")</div>
<h3>Albums</h3>
@for (var x = 0; x < @Model.Count; x++)
{
    <div>
       <span> Name: @Model[x].Name </span><span>Topic: @Model[x].Topic.ToString();</span> 
    </div>
   
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Home/Information.cshtml
@{
    ViewBag.Title = "Information";
}

<h2>Information</h2>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Home/Test.cshtml
@{    ViewBag.Title = "Index"; }

<div class="panel panel-primary">
    <div class="panel-heading">User Details</div>    <table class="table table-striped">
        @foreach (string key in Model.Keys)
        {
            <tr>                <th>@key</th>                <td>@Model[key]</td>            </tr>        }
    </table>
</div>