Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Lab_MVC_med_Javascript_och_Ajax.Models
{
    public class Comment
    {
        public int id { get; set; }
        public string content { get; set; }
        public int? PictureRefID { get; set; }
        [ForeignKey(name: "PictureRefID")]
        public virtual Picture Picture { get; set; }
        public Guid? UserRefID { get; set; }
        [ForeignKey(name:"UserRefID")]
        public virtual User User { get; set; }
    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab_MVC_med_Javascript_och_Ajax;
using Lab_MVC_med_Javascript_och_Ajax.Models;

namespace Lab_MVC_med_Javascript_och_Ajax.Controllers
{
    public class CommentsController : Controller
    {
        private GalleryDbContext db = new GalleryDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Picture);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create(int id)
        {
            //ViewBag.PictureRefID = new SelectList(db.Pictures, "id", "Title");
            Comment comment = new Comment();
            comment.PictureRefID = id;
            return View(comment);
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,content,PictureRefID")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index", "Gallery");
            }

            ViewBag.PictureRefID = new SelectList(db.Pictures, "id", "Title", comment.PictureRefID);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PictureRefID = new SelectList(db.Pictures, "id", "Title", comment.PictureRefID);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,content,PictureRefID")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PictureRefID = new SelectList(db.Pictures, "id", "Title", comment.PictureRefID);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Controllers/GalleryController.cs
using Lab_MVC_med_Javascript_och_Ajax.DBConnection;
using Lab_MVC_med_Javascript_och_Ajax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_MVC_med_Javascript_och_Ajax.Controllers
{
    public class GalleryController : Controller
    {    
        List<Picture> Pictures = CRUD.GetPictures();
        private GalleryDbContext db = new GalleryDbContext();
        public ActionResult Index()
        {           
            return View(Pictures);
        }
        public ActionResult Uppload()
        {
            return View();
        }
        public ActionResult Delete()
        {
            return View();
        }
        public ActionResult Show(int id)
        {
            var model = GetPictureFromDB(id);
            return View(model);
        }
        public ActionResult Comment(int id)
        {                  
            return View(((GetPictureFromDB(id)).FillAllData()));
        }

        private Picture GetPictureFromDB(int id)
        {
            return  Pictures.FirstOrDefault(x=> x.id == id);           
        }
    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Controllers/PictureController.cs
using Lab_MVC_med_Javascript_och_Ajax.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Lab_MVC_med_Javascript_och_Ajax.Controllers
{
    public class PictureController : Controller
    {

        private GalleryDbContext db = new GalleryDbContext();



        // GET: Pictures

        public ActionResult Index()

        {

            return View(db.Pictures.ToList());

        }

        public ActionResult Change(int? id)

        {

            return View();

        }



        // GET: Pictures/Details/5

        public ActionResult Details(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Picture picture = db.Pictures.Find(id);

            if (picture == null)

            {

                return HttpNotFound();

            }

            return View(picture);

        }



        // GET: Pictures/Create

        public ActionResult Create()

        {

            return View();

        }



        // POST: Pictures/Create

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Create(Picture picture, HttpPostedFileBase file)

        {
            if (file.ContentLength > 0)

            {
                file.SaveAs(Path.Combine(Server.MapPath("~/Saves"), file.FileName));
            picture.Title = file.FileName;
            picture.url = $@"/Saves/" + file.FileName;
            picture.Size = file.ContentLength;
           

           
                db.Pictures.Add(picture);
                db.SaveChanges();

                return RedirectToAction("Index", "Gallery");
            }
            return View(picture);

        }



        // GET: Pictures/Edit/5

        public ActionResult Edit(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Picture picture = db.Pictures.Find(id);

            if (picture == null)

            {

                return HttpNotFound();

            }

            return View(picture);

        }



        // POST: Pictures/Edit/5

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "id,Title,url,Size")] Picture picture)

        {

            if (ModelState.IsValid)

            {

                db.Entry(picture).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");

            }

            return View(picture);

        }



        // GET: Pictures/Delete/5

        public ActionResult Delete(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Picture picture = db.Pictures.Find(id);

            if (picture == null)

            {

                return HttpNotFound();

            }

            return View(picture);

        }



        // POST: Pictures/Delete/5

        [HttpPost, ActionName("Delete")]

        [ValidateAntiForgeryToken]

        public ActionResult DeleteConfirmed(int id)

        {

            Picture picture = db.Pictures.Find(id);

            var comments = db.Comments.Where(x => x.PictureRefID == id);

            //Delete all comments from db

            foreach (var item in comments)

            {

                db.Comments.Remove(item);

            }

            // Här använder jag min metod Theres (Delete the picturefile from server)

            RemoveFileFromServer((db.Pictures.FirstOrDefault(x => x.id == id).url));

            //delete Picture from db

            db.Pictures.Remove(picture);

            db.SaveChanges();



            return RedirectToAction("Index,Gallery");

        }



        protected override void Dispose(bool disposing)

        {

            if (disposing)

            {

                db.Dispose();

            }

            base.Dispose(disposing);

        }

        private bool RemoveFileFromServer(string path)

        {

            var fullPath = Request.MapPath(path);

            if (!System.IO.File.Exists(fullPath)) return false;



            try

            {

                System.IO.File.Delete(fullPath);

                return true;

            }

            catch (Exception e)

            {

                //  Debug.WriteLine(e.Message);

            }

            return false;

        }

    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Gallery/Comment.cshtml
<h2>Comment</h2>

<div class="row">
    <div class="col-xs-6 col-md-4">
        <div class="thumbnail">
            <img src="@Model.url" alt="...">
            <div class="caption">
                <h3>@Model.Title</h3>
                <p>Id: @Model.id</p>
                <p>Size: @Model.Size</p>

            </div>
        </div>
    </div>
    <div class="col-xs-6 col-md-4">
        <h4>Comments</h4>
        @foreach (var item in Model.Comments)
        {
            if (@item.UserRefID != null)
            {

                <p>-@item.content <small>(@item.User.email)</small></p>
            }
            else
            { <p>-@item.content <small>(Annonym)</small></p> }

        }
    </div>
</div>
<div>@Html.ActionLink("Back", "Index", "Gallery")</div>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Gallery/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Gallery/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

@Html.ActionLink("Uppload new picture", "Create", "Picture")

<div class="flex-container">
    @for (var x = 0; x < Model.Count; x++)
    {
        <article class="image-thumb">
            <a href="@Url.Action("Show","Gallery",new { id = Model[x].id }, null)">
                <img src="@Url.Content($"{Model[x].url}")" alt=". . .ALT. . .">
            </a>
        </article>
    }
</div>

    @*<div class="row">
            @for (var x = 0; x < Model.Count; x++)
            {
                <div class="col-xs-3">
                    <div class="thumbnail">
                        <img style="height:100px;" src="@Model[x].url" alt="...">
                        <div class="caption">
                            <h3>@Model[x].Title</h3>
                            <p>Size = @Model[x].Size</p>
                            <div>@Html.ActionLink("Comment", "Create", "Comments", new { id = Model[x].id }, null)</div>
                            <div>@Html.ActionLink("View picture", "Show", "Gallery", new { id = Model[x].id }, null)</div>
                            <div>@Html.ActionLink("See Comments", "Comment", "Gallery", new { id = Model[x].id }, null)<span>(@Model[x].Comments.Count)</span></div>
                            <div>@Html.ActionLink("Delete", "Delete", "Picture", new { id = Model[x].id }, null)</div>

                        </div>
                    </div>
                </div>
            }

        </div>*@
<style>
    .flex-container {
            display: -webkit-flex;
            display: flex;
            width: 100%;                
            flex-wrap: wrap;
    }

    .flex-item {             
     
            margin: 10px;
            transition: position 2s;
    }
</style>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Gallery/Show.cshtml
@{
    ViewBag.Title = "Show";
}

<h2>Show</h2>

<img src="@Model.url" alt="...">
<h1>Title = @Model.Title</h1>
<h2>Id = @Model.id</h2>
<h2>Size = @Model.Size b</h2>
<div>@Html.ActionLink("Back", "Index", "Gallery")</div>