Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab_MVC_med_Javascript_och_Ajax.Models
{
    public class Picture
    {
        public int id { get; set; }
        public string Title { get; set; }
        [Required]
        public string url { get; set; }
        [Required]
        public int Size { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public Picture()
        {
            this.Comments =new HashSet<Comment>();           
        }
    }
 
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Controllers/PictureController.cs
using Lab_MVC_med_Javascript_och_Ajax.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Lab_MVC_med_Javascript_och_Ajax.Controllers
{
    public class PictureController : Controller
    {

        private GalleryDbContext db = new GalleryDbContext();



        // GET: Pictures

        public ActionResult Index()

        {

            return View(db.Pictures.ToList());

        }

        public ActionResult Change(int? id)

        {

            return View();

        }



        // GET: Pictures/Details/5

        public ActionResult Details(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Picture picture = db.Pictures.Find(id);

            if (picture == null)

            {

                return HttpNotFound();

            }

            return View(picture);

        }



        // GET: Pictures/Create

        public ActionResult Create()

        {

            return View();

        }



        // POST: Pictures/Create

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Create(Picture picture, HttpPostedFileBase file)

        {
            if (file.ContentLength > 0)

            {
                file.SaveAs(Path.Combine(Server.MapPath("~/Saves"), file.FileName));
            picture.Title = file.FileName;
            picture.url = $@"/Saves/" + file.FileName;
            picture.Size = file.ContentLength;
           

           
                db.Pictures.Add(picture);
                db.SaveChanges();

                return RedirectToAction("Index", "Gallery");
            }
            return View(picture);

        }



        // GET: Pictures/Edit/5

        public ActionResult Edit(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Picture picture = db.Pictures.Find(id);

            if (picture == null)

            {

                return HttpNotFound();

            }

            return View(picture);

        }



        // POST: Pictures/Edit/5

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "id,Title,url,Size")] Picture picture)

        {

            if (ModelState.IsValid)

            {

                db.Entry(picture).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");

            }

            return View(picture);

        }



        // GET: Pictures/Delete/5

        public ActionResult Delete(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Picture picture = db.Pictures.Find(id);

            if (picture == null)

            {

                return HttpNotFound();

            }

            return View(picture);

        }



        // POST: Pictures/Delete/5

        [HttpPost, ActionName("Delete")]

        [ValidateAntiForgeryToken]

        public ActionResult DeleteConfirmed(int id)

        {

            Picture picture = db.Pictures.Find(id);

            var comments = db.Comments.Where(x => x.PictureRefID == id);

            //Delete all comments from db

            foreach (var item in comments)

            {

                db.Comments.Remove(item);

            }

            // Här använder jag min metod Theres (Delete the picturefile from server)

            RemoveFileFromServer((db.Pictures.FirstOrDefault(x => x.id == id).url));

            //delete Picture from db

            db.Pictures.Remove(picture);

            db.SaveChanges();



            return RedirectToAction("Index,Gallery");

        }



        protected override void Dispose(bool disposing)

        {

            if (disposing)

            {

                db.Dispose();

            }

            base.Dispose(disposing);

        }

        private bool RemoveFileFromServer(string path)

        {

            var fullPath = Request.MapPath(path);

            if (!System.IO.File.Exists(fullPath)) return false;



            try

            {

                System.IO.File.Delete(fullPath);

                return true;

            }

            catch (Exception e)

            {

                //  Debug.WriteLine(e.Message);

            }

            return false;

        }

    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab_MVC_med_Javascript_och_Ajax.Models;
using System.IO;
using Lab_MVC_med_Javascript_och_Ajax.DBConnection;

namespace Lab_MVC_med_Javascript_och_Ajax.Controllers
{
    public class PicturesController : Controller
    {
        private GalleryDbContext db = new GalleryDbContext();

        // GET: Pictures
        public ActionResult Index()
        {
            return View(db.Pictures.ToList());
        }
        public ActionResult Change(int? id)
        {
            return View();
        }

        // GET: Pictures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // GET: Pictures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pictures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Picture picture, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                file.SaveAs(Path.Combine(Server.MapPath("~/Saves"), file.FileName));
                picture.url = $@"/Saves/" + file.FileName;
                picture.Size = file.ContentLength;
                db.Pictures.Add(picture);
                db.SaveChanges();
                return RedirectToAction("Index", "Gallery");
            }

            return View(picture);
        }

        // GET: Pictures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: Pictures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Title,url,Size")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(picture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(picture);
        }

        // GET: Pictures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: Pictures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picture picture = db.Pictures.Find(id);
            var comments = db.Comments.Where(x => x.PictureRefID == id);
            //Delete all comments from db
            foreach (var item in comments)
            {
                db.Comments.Remove(item);
            }
            // Här använder jag min metod Theres (Delete the picturefile from server)
            RemoveFileFromServer((db.Pictures.FirstOrDefault(x => x.id == id).url));
            //delete Picture from db
            db.Pictures.Remove(picture);
            db.SaveChanges();

            return RedirectToAction("Index,Gallery");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private bool RemoveFileFromServer(string path)
        {
            var fullPath = Request.MapPath(path);
            if (!System.IO.File.Exists(fullPath)) return false;

            try 
            {
                System.IO.File.Delete(fullPath);
                return true;
            }
            catch (Exception e)
            {
              //  Debug.WriteLine(e.Message);
            }
            return false;
        }
    }
}

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Pictures/Change.cshtml
@model Lab_MVC_med_Javascript_och_Ajax.Models.Picture

@{
    ViewBag.Title = "Change";
}

<h2>Change</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Details", "Show","Gallery", new { id = Model.id }, null)
</div>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Pictures/Create.cshtml
@model Lab_MVC_med_Javascript_och_Ajax.Models.Picture

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pictures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                <input type="file" name="file" id="file" />
                @Html.ValidationMessage("error")
            </div>
        </div>    

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Pictures/Delete.cshtml
@model Lab_MVC_med_Javascript_och_Ajax.Models.Picture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Pictures/Details.cshtml
@model Lab_MVC_med_Javascript_och_Ajax.Models.Picture

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Pictures/Edit.cshtml
@model Lab_MVC_med_Javascript_och_Ajax.Models.Picture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lab_MVC_med_Javascript_och_Ajax/Lab_MVC_med_Javascript_och_Ajax/Views/Pictures/Index.cshtml
@model IEnumerable<Lab_MVC_med_Javascript_och_Ajax.Models.Picture>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>